services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_HOST=mysql
      - MB_DB_PORT=3306
      - MB_DB_DBNAME=metabasedb
      - MB_DB_USER=metabase-user
      - MB_DB_PASS=metabase-pass
      - METABASE_DATABASE=metabase
      - METABASE_USER=metabase
      - METABASE_PASSWORD=metabase
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    tty: true
    healthcheck:
      test: curl --fail -I http://localhost3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - "./metabase/initdb.d:/docker-entrypoint-initdb.d"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - internal

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=metabasedb
      - MYSQL_USER=metabase-user
      - MYSQL_PASSWORD=metabase-pass
      - MYSQL_ROOT_HOST=%
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mysql-data:
