services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    tty: true
    healthcheck:
      test: curl --fail -I http://localhost3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
